### ISSUE TITLE
Naming conflict with `srm` (secure rm)

### ISSUE THREAD

**Issue by Conan-Kudo** [CuarzoSoftware/SRM#15]
I'm working on [packaging louvre for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2297711), and as part of that, I [packaged this](https://bugzilla.redhat.com/show_bug.cgi?id=2297708). During the review process, it was identified that the name of this conflicts with the existence of `srm`, a tool for securely deleting things. I _think_ I've been able to work around it for now, but you may want to consider changing the name of this project.

**Comment by ehopperdietzel** [comment]
Hi, thank you so much! I think `libsrm` is perfect since it matches the name on [Debian](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libsrm), and I don't see other packages on Fedora using it. So, is `libsrm` okay? If not, I'll change it.

**Comment by Conan-Kudo** [comment]
We should be good for now, though I do think you should consider it regardless.

**Comment by ehopperdietzel** [comment]
I will, thank you!
