### ISSUE TITLE
cannot build on device withonly gles support

### ISSUE THREAD

**Issue by Roogephy** [CuarzoSoftware/SRM#16]
cannot build on device withonly gles support
my embedeed device not support desktop opengl but opengl es 3.1,the source depend on desktop opengl , cannot build.
`[1/30] Compiling C object libSRM.so.0.p/lib_SRMBuffer.c.o
FAILED: libSRM.so.0.p/lib_SRMBuffer.c.o 
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/x86_64-sdrvsdk-linux/usr/bin/aarch64-sdrv-linux/aarch64-sdrv-linux-gcc -IlibSRM.so.0.p -I. -I.. -I../lib -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/home/roogephy/projects/SRM/libdisplay-info-main/buildArm64/out/include -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -DSRM_LITTLE_ENDIAN=1 -DSRM_BIG_ENDIAN=0 --sysroot /home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux -fPIC -DEGL_NO_X11 -MD -MQ libSRM.so.0.p/lib_SRMBuffer.c.o -MF libSRM.so.0.p/lib_SRMBuffer.c.o.d -o libSRM.so.0.p/lib_SRMBuffer.c.o -c ../lib/SRMBuffer.c
../lib/SRMBuffer.c:1:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
[2/30] Compiling C object libSRM.so.0.p/lib_SRMFormat.c.o
FAILED: libSRM.so.0.p/lib_SRMFormat.c.o 
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/x86_64-sdrvsdk-linux/usr/bin/aarch64-sdrv-linux/aarch64-sdrv-linux-gcc -IlibSRM.so.0.p -I. -I.. -I../lib -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/home/roogephy/projects/SRM/libdisplay-info-main/buildArm64/out/include -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -DSRM_LITTLE_ENDIAN=1 -DSRM_BIG_ENDIAN=0 --sysroot /home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux -fPIC -DEGL_NO_X11 -MD -MQ libSRM.so.0.p/lib_SRMFormat.c.o -MF libSRM.so.0.p/lib_SRMFormat.c.o.d -o libSRM.so.0.p/lib_SRMFormat.c.o -c ../lib/SRMFormat.c
../lib/SRMFormat.c:4:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
[7/30] Compiling C object libSRM.so.0.p/lib_SRMTypes.c.o
FAILED: libSRM.so.0.p/lib_SRMTypes.c.o 
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/x86_64-sdrvsdk-linux/usr/bin/aarch64-sdrv-linux/aarch64-sdrv-linux-gcc -IlibSRM.so.0.p -I. -I.. -I../lib -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/home/roogephy/projects/SRM/libdisplay-info-main/buildArm64/out/include -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -DSRM_LITTLE_ENDIAN=1 -DSRM_BIG_ENDIAN=0 --sysroot /home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux -fPIC -DEGL_NO_X11 -MD -MQ libSRM.so.0.p/lib_SRMTypes.c.o -MF libSRM.so.0.p/lib_SRMTypes.c.o.d -o libSRM.so.0.p/lib_SRMTypes.c.o -c ../lib/SRMTypes.c
../lib/SRMTypes.c: In function ‘srmGetConnectorTypeString’:
../lib/SRMTypes.c:65:14: error: ‘DRM_MODE_CONNECTOR_WRITEBACK’ undeclared (first use in this function); did you mean ‘DRM_MODE_CONNECTOR_VIRTUAL’?
         case DRM_MODE_CONNECTOR_WRITEBACK:   return "writeback";
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
              DRM_MODE_CONNECTOR_VIRTUAL
../lib/SRMTypes.c:65:14: note: each undeclared identifier is reported only once for each function it appears in
[9/30] Compiling C object libSRM.so.0.p/lib_private_modes_SRMRenderModeCPU.c.o
FAILED: libSRM.so.0.p/lib_private_modes_SRMRenderModeCPU.c.o 
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/x86_64-sdrvsdk-linux/usr/bin/aarch64-sdrv-linux/aarch64-sdrv-linux-gcc -IlibSRM.so.0.p -I. -I.. -I../lib -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/home/roogephy/projects/SRM/libdisplay-info-main/buildArm64/out/include -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -DSRM_LITTLE_ENDIAN=1 -DSRM_BIG_ENDIAN=0 --sysroot /home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux -fPIC -DEGL_NO_X11 -MD -MQ libSRM.so.0.p/lib_private_modes_SRMRenderModeCPU.c.o -MF libSRM.so.0.p/lib_private_modes_SRMRenderModeCPU.c.o.d -o libSRM.so.0.p/lib_private_modes_SRMRenderModeCPU.c.o -c ../lib/private/modes/SRMRenderModeCPU.c
../lib/private/modes/SRMRenderModeCPU.c:17:10: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
          ^~~~~~~~~
compilation terminated.
[14/30] Compiling C object libSRM.so.0.p/lib_SRMConnector.c.o
FAILED: libSRM.so.0.p/lib_SRMConnector.c.o 
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/x86_64-sdrvsdk-linux/usr/bin/aarch64-sdrv-linux/aarch64-sdrv-linux-gcc -IlibSRM.so.0.p -I. -I.. -I../lib -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/home/roogephy/projects/SRM/libdisplay-info-main/buildArm64/out/include -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -DSRM_LITTLE_ENDIAN=1 -DSRM_BIG_ENDIAN=0 --sysroot /home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux -fPIC -DEGL_NO_X11 -MD -MQ libSRM.so.0.p/lib_SRMConnector.c.o -MF libSRM.so.0.p/lib_SRMConnector.c.o.d -o libSRM.so.0.p/lib_SRMConnector.c.o -c ../lib/SRMConnector.c
In file included from ../lib/private/modes/SRMRenderModeCommon.h:5:0,
                 from ../lib/SRMConnector.c:1:
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/xf86drmMode.h:520:64: error: unknown type name ‘size_t’; did you mean ‘__ssize_t’?
 extern int drmModeCreatePropertyBlob(int fd, const void *data, size_t size,
                                                                ^~~~~~
                                                                __ssize_t
../lib/SRMConnector.c: In function ‘srmConnectorSetCustomScanoutBuffer’:
../lib/SRMConnector.c:855:18: warning: implicit declaration of function ‘drmGetFormatName’; did you mean ‘srmDeviceGetName’? [-Wimplicit-function-declaration]
                  drmGetFormatName(oldFmt),
                  ^~~~~~~~~~~~~~~~
                  srmDeviceGetName
../lib/SRMConnector.c:852:73: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
         SRMError("[%s][%s] Failed to set custom scanout buffer. Format %s not supported by primary plane. Trying alpha substitute format %s",
                                                                        ~^
                                                                        %d
../lib/SRMConnector.c:855:18:
                  drmGetFormatName(oldFmt),
                  ~~~~~~~~~~~~~~~~~~~~~~~~                                
../lib/SRMConnector.c:852:139: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Wformat=]
         SRMError("[%s][%s] Failed to set custom scanout buffer. Format %s not supported by primary plane. Trying alpha substitute format %s",
                                                                                                                                          ~^
                                                                                                                                          %d
../lib/SRMConnector.c:856:18:
                  drmGetFormatName(buffer->scanout.fmt.format));
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                              
../lib/SRMConnector.c:865:22: warning: implicit declaration of function ‘drmGetFormatModifierName’ [-Wimplicit-function-declaration]
                      drmGetFormatModifierName(buffer->scanout.fmt.modifier));
                      ^~~~~~~~~~~~~~~~~~~~~~~~
../lib/SRMConnector.c:861:99: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
             SRMError("[%s][%s] Failed to set custom scanout buffer. Unsupported format/modifier: %s - %s.",
                                                                                                  ~^
                                                                                                  %d
../lib/SRMConnector.c:864:22:
                      drmGetFormatName(buffer->scanout.fmt.format),
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                  
../lib/SRMConnector.c:861:104: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Wformat=]
             SRMError("[%s][%s] Failed to set custom scanout buffer. Unsupported format/modifier: %s - %s.",
                                                                                                       ~^
                                                                                                       %d
../lib/SRMConnector.c:865:22:
                      drmGetFormatModifierName(buffer->scanout.fmt.modifier));
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                             
../lib/SRMConnector.c:919:130: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
             SRMError("[%s][%s] Failed to set custom scanout buffer using drmModeAddFB(), could not get depth and bpp for format %s.",
                                                                                                                                 ~^
                                                                                                                                 %d
../lib/SRMConnector.c:922:22:
                      drmGetFormatName(buffer->scanout.fmt.format));
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                 
[16/30] Compiling C object libSRM.so.0.p/lib_private_SRMPlanePrivate.c.o
FAILED: libSRM.so.0.p/lib_private_SRMPlanePrivate.c.o 
/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/x86_64-sdrvsdk-linux/usr/bin/aarch64-sdrv-linux/aarch64-sdrv-linux-gcc -IlibSRM.so.0.p -I. -I.. -I../lib -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/home/roogephy/projects/SRM/libdisplay-info-main/buildArm64/out/include -I/home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -DSRM_LITTLE_ENDIAN=1 -DSRM_BIG_ENDIAN=0 --sysroot /home/roogephy/roogephy/x9u/linux/waylandSysroots/sysroots/aarch64-sdrv-linux -fPIC -DEGL_NO_X11 -MD -MQ libSRM.so.0.p/lib_private_SRMPlanePrivate.c.o -MF libSRM.so.0.p/lib_private_SRMPlanePrivate.c.o.d -o libSRM.so.0.p/lib_private_SRMPlanePrivate.c.o -c ../lib/private/SRMPlanePrivate.c
../lib/private/SRMPlanePrivate.c: In function ‘srmPlaneUpdateInFormats’:
../lib/private/SRMPlanePrivate.c:162:13: error: unknown type name ‘drmModeFormatModifierIterator’
             drmModeFormatModifierIterator iter = {0};
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/private/SRMPlanePrivate.c:164:20: warning: implicit declaration of function ‘drmModeFormatModifierBlobIterNext’ [-Wimplicit-function-declaration]
             while (drmModeFormatModifierBlobIterNext(blob, &iter))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/private/SRMPlanePrivate.c:165:63: error: request for member ‘fmt’ in something not a structure or union
                 srmFormatsListAddFormat(plane->inFormats, iter.fmt, iter.mod);
                                                               ^
../lib/private/SRMPlanePrivate.c:165:73: error: request for member ‘mod’ in something not a structure or union
                 srmFormatsListAddFormat(plane->inFormats, iter.fmt, iter.mod);
                                                                         ^
[18/30] Compiling C object libSRM.so.0.p/lib_private_modes_SRMRenderModeCommon.c.o
../lib/private/modes/SRMRenderModeCommon.c: In function ‘srmRenderModeCommonSearchNonLinearModifier’:
../lib/private/modes/SRMRenderModeCommon.c:1400:17: warning: implicit declaration of function ‘drmGetFormatName’; did you mean ‘drmGetContextTag’? [-Wimplicit-function-declaration]
                 drmGetFormatName(fmt->format),
                 ^~~~~~~~~~~~~~~~
                 drmGetContextTag
../lib/private/modes/SRMRenderModeCommon.c:1401:17: warning: implicit declaration of function ‘drmGetFormatModifierName’ [-Wimplicit-function-declaration]
                 drmGetFormatModifierName(fmt->modifier));
                 ^~~~~~~~~~~~~~~~~~~~~~~~
../lib/private/modes/SRMRenderModeCommon.c:1397:56: warning: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Wformat=]
             SRMDebug("[%s] Connector %d using format: %s - %s.",
                                                       ~^
                                                       %d
../lib/private/modes/SRMRenderModeCommon.c:1400:17:
                 drmGetFormatName(fmt->format),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
../lib/private/modes/SRMRenderModeCommon.c:1397:61: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Wformat=]
             SRMDebug("[%s] Connector %d using format: %s - %s.",
                                                            ~^
                                                            %d
../lib/private/modes/SRMRenderModeCommon.c:1401:17:
                 drmGetFormatModifierName(fmt->modifier));
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
ninja: build stopped: subcommand failed.
`

**Comment by ehopperdietzel** [comment]
OpenGL is required to access certain headers (`No such file or directory #include <GL/gl.h>`). 
Additionally, it appears that your `libdrm` version or kernel may be outdated, as there are several errors indicating undefined DRM functions.

**Comment by ehopperdietzel** [comment]
I've just added the min required versions for each dep
